In [1]:
import numpy as np
import matplotlib.pyplot as plt
import h5py

%matplotlib inline

In [6]:
a = np.random.randn(5) # es mejor poner (5,1) --> rows, columns
print(a)

[-1.41368918 -0.3590532  -0.69698136  1.50151511  1.17681524]


In [10]:
print(a.shape)
print(a.T)
print(np.dot(a,a.T))

(5, 1)
[[-0.38781078 -0.91672157 -0.33155651  0.4014374  -1.25419899]]
[[ 0.1503972   0.3555145   0.12858119 -0.15568175  0.48639189]
 [ 0.3555145   0.84037843  0.30394501 -0.36800633  1.14975126]
 [ 0.12858119  0.30394501  0.10992972 -0.13309919  0.41583785]
 [-0.15568175 -0.36800633 -0.13309919  0.16115199 -0.50348239]
 [ 0.48639189  1.14975126  0.41583785 -0.50348239  1.57301511]]


In [11]:
a = np.random.randn(5,1)
print(a)
print(a.T)

[[-0.15713258]
 [ 0.55785584]
 [-0.18331992]
 [ 1.32883904]
 [-0.21032649]]
[[-0.15713258  0.55785584 -0.18331992  1.32883904 -0.21032649]]


In [12]:
a = np.random.randn(1,5)
print(a)

[[0.61873107 0.28355948 0.92404356 1.15750619 0.41937563]]


In [13]:
a = np.random.randn(2, 3) # a.shape = (2, 3)
b = np.random.randn(2, 1) # b.shape = (2, 1)
c = a + b
print(c.shape)

(2, 3)


In [16]:
a = np.random.randn(12288, 150) # a.shape = (12288, 150)
b = np.random.randn(150, 45) # b.shape = (150, 45)
c = np.dot(a,b)
print(c.shape)

(12288, 45)


In [22]:
a = np.random.randn(3,4)
b = np.random.randn(4,1)
c = np.dot(a,b)
print(c.shape)


(3, 1)


In [24]:
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c = a*b
print(c.shape)

(3, 3)


In [ ]:
j=(a*b)+(a*c)-(b+c)
